name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24.11.0"
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      # - name: commitlint
      #   uses: wagoid/commitlint-github-action@v5.0.2
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [[ "$GITHUB_REF" = "refs/heads/main" ]]; then
            GITHUB_TOKEN=$GH_TOKEN npx semantic-release --verbose
          else
            echo "skipping release on branch $GITHUB_REF"
          fi
